### ISSUE TITLE
SoftLayer light stemcells should not include the version in the name

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/bosh-softlayer-cpi-release#27]
The metadata in all stemcells located in  `https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/` use names that include the version. This makes it impossible to call out a stemcell name in manifest templates that reference `latest` as the version.

> NOTE: I'm not referring to the filename; I'm talking about the metadata.

``` yaml
name: light-bosh-stemcell-3232.4-softlayer-esxi-ubuntu-trusty-go_agent # wrong - has version
version: "3232.4"
bosh_protocol: 1
sha1: MTE0NDk0OTpmMjY3YjhlNi0yNWRmLTQ0MjAtOWQzYi1kYWM5MjMyZTNlMmTaOaPuXmtLDTJVv++VYBiQr9gHCQ==
operating_system: ubuntu-trusty
cloud_properties:
  infrastructure: softlayer
  architecture: x86_64
  root_device_name: /dev/xvda
  version: "3232.4"
  virtual-disk-image-id: 1144949
  virtual-disk-image-uuid: f267b8e6-25df-4420-9d3b-dac9232e3e2d
  datacenter-name: lon02
```

Please update your stemcell build process so the names resemble what is used in aws stemcells:

``` yaml

---
name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent # right - does not have version
version: '3232.8'
```
