### ISSUE TITLE
`SHA1 mismatch` with non-ruby CLI `bosh create-release --force`

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry-incubator/bosh-softlayer-cpi-release#31]
I plan to submit a PR to fix.

```
bosh create-release --force --with-tarball
Blob download 'golang_1.6.2/go1.6.2.linux-amd64.tar.gz' (85 MB) (id: 4af848c7-c895-43cd-a9cd-b75a6bdea79a sha1: YjgzMThiMDlkZTA2MDc2ZDUzOTdlNmVjMThlYmVmM2I0NWNkMzE1ZA==) started

Blob download 'golang_1.6.2/go1.6.2.linux-amd64.tar.gz' (id: 4af848c7-c895-43cd-a9cd-b75a6bdea79a) failed

Getting blob '4af848c7-c895-43cd-a9cd-b75a6bdea79a' for path 'golang_1.6.2/go1.6.2.linux-amd64.tar.gz':
  Getting blob from inner blobstore:
    SHA1 mismatch. Expected YjgzMThiMDlkZTA2MDc2ZDUzOTdlNmVjMThlYmVmM2I0NWNkMzE1ZA==, got b8318b09de06076d5397e6ec18ebef3b45cd315d for blob /Users/cunnie/.bosh/tmp/bosh-s3-blob200517173

Exit code 1
```

Contents of `blobs.yml`

``` yaml
golang_1.6.2/go1.6.2.linux-amd64.tar.gz:
  object_id: 4af848c7-c895-43cd-a9cd-b75a6bdea79a
  sha: !binary |-
    YjgzMThiMDlkZTA2MDc2ZDUzOTdlNmVjMThlYmVmM2I0NWNkMzE1ZA==
  size: 84840658
```
