### ISSUE TITLE
Unexpected deployment configuration

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-incubator/bosh-softlayer-cpi-release#41]
When I was deploying bosh via bosh-init, I removed the section for a public network in my bosh.yml.

Specifically:
```
resource_pools:
  - name: vms
    cloud_properties
    PrimaryNetworkComponent:  <---- this line and below
       NetworkVlan:
          Id: <pub vlan>
```
but I still got a public IP address after I deployed. When digging through the code, I saw a property to set (`PrivateNetworkOnlyFlag`), which when set should give me only a private IP address.

It would be nice to have an updated property configuration list.
